import json
from datetime import datetime, timezone
from pathlib import Path

from security_gate.scanner.base import Finding, Severity

_SEVERITY_EMOJI = {
    Severity.CRITICAL: "🔴",
    Severity.HIGH: "🟠",
    Severity.MEDIUM: "🟡",
    Severity.LOW: "🔵",
    Severity.INFO: "⚪",
}

_GATE_RESULT = {True: "✅ GATE PASSED", False: "❌ GATE BLOCKED"}


def _counts(findings: list[Finding]) -> dict:
    counts = {s: 0 for s in Severity}
    for f in findings:
        counts[f.severity] += 1
    return counts


def gate_passed(findings: list[Finding]) -> bool:
    counts = _counts(findings)
    return counts[Severity.CRITICAL] == 0 and counts[Severity.HIGH] == 0


def generate_json(findings: list[Finding], repo_path: str) -> str:
    counts = _counts(findings)
    return json.dumps({
        "generated": datetime.now(timezone.utc).isoformat(),
        "repo": repo_path,
        "gate": "PASSED" if gate_passed(findings) else "BLOCKED",
        "summary": {s.value: counts[s] for s in Severity},
        "findings": [f.to_dict() for f in sorted(findings, key=lambda x: x.sort_key())],
    }, indent=2)


def generate_markdown(findings: list[Finding], repo_path: str) -> str:
    counts = _counts(findings)
    passed = gate_passed(findings)
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    total = len(findings)

    lines = [
        f"# security-gate report — {Path(repo_path).name}",
        f"*Generated: {now}*",
        "",
        f"## {_GATE_RESULT[passed]}",
        "",
        "| Severity | Count |",
        "|----------|-------|",
    ]
    for sev in Severity:
        emoji = _SEVERITY_EMOJI[sev]
        lines.append(f"| {emoji} {sev.value} | {counts[sev]} |")

    lines += ["", f"**{total} finding{'s' if total != 1 else ''} total**", ""]

    if not findings:
        lines.append("No issues detected.")
        return "\n".join(lines)

    lines += ["---", "", "## Findings", ""]

    by_scanner: dict[str, list[Finding]] = {}
    for f in sorted(findings, key=lambda x: x.sort_key()):
        by_scanner.setdefault(f.scanner, []).append(f)

    for scanner, scanner_findings in by_scanner.items():
        lines += [f"### {scanner}", ""]
        for f in scanner_findings:
            emoji = _SEVERITY_EMOJI[f.severity]
            lines += [
                f"**{emoji} {f.severity.value}** — `{f.file}:{f.line}`",
                f"> {f.detail}",
                f"```",
                f"{f.match}",
                f"```",
                f"*Checklist:* `{f.checklist_item}`",
                "",
            ]

    lines += [
        "---",
        "",
        "## Manual sign-off required",
        "",
        "The following gate items require human judgement — the scanner cannot verify them automatically:",
        "",
        "- [ ] Trust boundary map complete and reviewed",
        "- [ ] Adversarial input paths assessed",
        "- [ ] HF model provenance verified (SHA checksum pinned)",
        "- [ ] Offline inference confirmed (network capture verification)",
        "- [ ] Data retention policy defined and implemented",
        "- [ ] Test fixtures confirmed synthetic (no real IOCs/IPs/payloads)",
        "",
        "*Generated by [security-gate](https://github.com/LeightonSec/security-gate) — LeightonSec*",
    ]

    return "\n".join(lines)
